---
- hosts: localhost
  tasks: 
    - rds:
        command: replicate
        instance_name: replica-ansible-database
        source_instance: Ansible-database
        region: us-east-1
      register: rds
      
    - debug:
         var: rds  
