--- 
- hosts: localhost
  tasks: 
    - name: "Set " 
      iam_password_policy: 
        allow_pw_change: true
        min_pw_length: 8
        pw_expire: false
        pw_max_age: 60
        pw_reuse_prevent: 5
        require_lowercase: true
        require_numbers: true
        require_symbols: false
        require_uppercase: true
        state: present
