---
#VPC

vpc_cidr: 10.0.0.0/16
vpc_name: "Ansible VPC"

# subnet 

subnet_name1: "Ansible Subnet1"
subnet_cidr1: 10.0.1.0/24
subnet_name2: "Ansible Subnet2"
subnet_cidr2: 10.0.2.0/24
subnet_name3: "Ansible Subnet3"
subnet_cidr3: 10.0.3.0/24
# Internet Gateway Name

igw_name: "Traffic IGW"

security_group: "Nitesh_Security_Grp"

ec2_tag: "Webserver"

route_name: "Ansible Route"

key_name: "ansibleLearn"
