---
- hosts: localhost
  tasks:
    - name: Create IAM role with custom trust relationship
      iam:
       iam_type: role
       name: EC2TestRole
       state: present
       trust_policy:
          Version: '2012-10-17'
          Statement:
             - Action: sts:AssumeRole
               Effect: Allow
               Principal:
                 Service: ec2.amazonaws.com
