---
- hosts: localhost 
  tasks: 

      - name: Create an EC2 key
        ec2_key:
          name: ansiblelearn.itlearn360
        register: ec2_key

      - name: Save private key
        copy:
          content: "{{ ec2_key.key.private_key }}" 
          dest: "/etc/ansible/misscelenous/keys_ansible.pem" 
          mode: 0600 
        when: ec2_key.changed 

      - debug:
           var: ec2_key
